#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp -r 0.org 0
runApplication setFields

# Decompose
runApplication decomposePar

# Run
runParallel `getApplication` 

# Reconstruct
runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
